$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

properties:
    seeds:
        type: string
    outdir: 
        type: string
    logdir: 
        type: string


    parameters:
        properties:
            pyscenic:
                type: object
                properties:
                    loom_matrix:
                        type: string
                    tfs_file:
                        type: string
                    method:
                        type: string
                    num_workers:
                        type: integer
                    extra:
                        type: string
    
    resources:
        properties:
            default:
                type: object
                properties:
                    threads:
                        type: integer
                    mem_mb:
                        type: integer
                    walltime:
                        type: integer

            pyscenic:
                type: object
                properties:
                    threads:
                        type: integer
                    mem_mb:
                        type: integer
                    walltime:
                        type: integer

required:
    - seeds
